title: Andy's Lab
description: Welcome to Andy's portfolio! Bookmark this to keep an eye on Andy's project updates!
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-feed
email: andyyangsemail@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: zongye-yang
github_username: andyzyang
